### ISSUE TITLE
Build project prototype

### ISSUE THREAD

**Issue by jazzyfresh** [jazzyfresh/cmsi3801#8]
- [ ] build front end
- [ ] build back end
  - [ ] api server - use flask library, instantiate flask object
    - [ ] each http request => calls function in webcrawler
  - [ ] web crawler - write web crawler class, instantiate object in api server
  - [ ] database
